steps:
  - label: Build the docker environment
    command: make dockerenvbuild

  - wait

  - label: Build python packages
    command: mkdir -p dist && .buildkite/build_whl.sh && docker container prune -f
  
  - wait

  - label: Build windows installer
    command: .buildkite/build_windows_installer.sh

  - wait

  - label: Upload artifacts
    command: .buildkite/setup_and_upload_artifacts.sh && docker image prune -f
