steps:
  - label: Build the docker environment
    command: make dockerenvbuild

  - wait

  - label: Build the python packages
    command: mkdir -p dist && .buildkite/build_and_artifact_upload.sh && docker container prune -f